### PR TITLE
pk-client: Refactor PkClientState lifecycle handling to fix leaks

### LINKED ISSUE #709: pkmon: GTask finalized without ever returning (using g_task_return_*())
```sh
$ pkmon
...
...
(pkmon:4086): GLib-GIO-CRITICAL **: 17:29:46.168: GTask 0x55aa9147cf60 (source object: 0x55aa9147aa30, source tag: 0x7f1b39a3b1c0) finalized without ever returning (using g_task_return_*()). This potentially indicates a bug in the program.
/8_edaceddb	allow_cancel 1
/8_edaceddb	percentage   -1
/8_edaceddb	role         search-file
/8_edaceddb	sender       /usr/bin/gnome-software
/8_edaceddb	status       wait
```

### PR DESCRIPTION
**Pull request by pwithnall**
This refactors the lifecycle of `PkClientState` a bit to eliminate some leaks I was seeing in gnome-software. It potentially also fixes #709, although I’ve only briefly tested that.

The main changes are that now:
 * `PkClient` holds a strong ref on every `PkClientState`
 * `PkClientState` no longer holds a strong ref on `PkClient`
 * A few code paths were fixed where `pk_client_state_finish()` was not called to finish a `PkClientState`
 * Each `PkClientState` is now added to `client->calls` as soon as it’s created, rather than after two async calls, which fixes cancellation of operations while either of those two calls are in flight
 * Lifecycle management of the `PkClientState` for `pk_client_get_progress_async()` has been made consistent with the rest of the code (it previously had its own outdated copy of `pk_client_state_finish()`)

The rest of the changes are cleanups or smaller fixes.

I’ve tested this for a few hours with a copy of gnome-software `main` with asan enabled. Previously it would leak about 500KB (directly and indirectly) from `gs_plugin_packagekit_auto_prepare_update_thread()` when using the following test setup:
 1. `LSAN_OPTIONS=report_objects=1,suppressions=supp.txt gnome-software &> out.log`
 2. Wait for it to load, and wait for `stat /var/lib/PackageKit/prepared-update` to succeed
 3. `sudo rm /var/lib/PackageKit/prepared-update` and wait 30s to trigger a prepared-updates check in gnome-software
 4. Wait for `stat /var/lib/PackageKit/prepared-update` to succeed again
 5. `gnome-software --quit` to cause gnome-software to exit gracefully and allow lsan to assess the damage

With these changes (and https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/2296) I get no leaks.

`supp.txt` is the following, to minimise noise from unrelated leaks (and false positives):
```
leak:as_xml_add_text_prop
leak:gsk_gpu_node_processor_add_node
leak:pango_cairo_fc_font_map_fontset_key_substitute
leak:FcFontSetMatch
leak:_gtk_css_reference_value_new
```

I’ll continue to test this with my background instance of `gnome-software`, but it’s ready for review and there’s nothing (from my point of view) blocking merge.

### CODE REVIEW

**Comment by ximion** [comment]
I'll be at a week-long conference next week (and need to prepare the flight to it) - I'll try to review this sooner, but if that doesn't work out, apologies in advance for only reviewing in ~2 weeks!

**Comment by sidt4** [comment]
I've applied `PackageKit` git + this MR on my system live.  `pkmon` is usable at last.

Thanks a lot @pwithnall!

**Comment by tintou** [comment]
Thank you, this looks great!

File: lib/packagekit-glib2/pk-client.c [hunk 1]
```diff
@@ -249,9 +255,11 @@ pk_client_state_finish (PkClientState *state, GError *error)
 
 	/* remove from list */
 	pk_client_state_remove (state->client, state);
+	/* `state_owned` may be the only strong ref to `state` remaining after this point */
 
 	/* mark the state as finished */
 	g_clear_object (&state->res);
+
```
Comment (ximion) [inline lib/packagekit-glib2/pk-client.c:262]: nit: Extra linebreak

**Review by ximion — APPROVED** [review]
This looks and works great! Thank you so much for the detailed commit messages, they helped immensely to wrap my head around why certain changes were made - I wish all PRs were like this! ^^

I tested this for about a day as well, and noticed no issues, and my only note is a whitespace nitpick... Do you want to resolve that? In any case, I'd merge this soon and we should have a release to include the change soon as well, I think.

**Comment by sidt4** [comment]
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2873 might be related to this change. Not sure.
