### PR TITLE
Fix issue #342 core-dump using alpm backend with hookdirs config set

### LINKED ISSUE #342: PackageKit service fails with a core-dump due to unsupported directive HookDir in pacman.conf.
**PackageKit version**

> 1.1.12-1

**Used distribution**

 > Manjaro Stable

**Expected behaviour you didn't see**

 > PackageKit service should be able to parse a standard pacman.conf file without core dumping. Being able to deal with unknown directives could be the best solution for parameters that are not relevant to PackageKit working.

**Unexpected behaviour you saw**

 > The PackageKit service fails with a core dump when it encounters the unknown directive `HookDir`.

```
● packagekit.service - PackageKit Daemon
   Loaded: loaded (/usr/lib/systemd/system/packagekit.service; static; vendor preset: disabled)
   Active: failed (Result: core-dump) since Thu 2019-09-26 16:52:37 -03; 2min 38s ago
  Process: 31837 ExecStart=/usr/lib/PackageKit/packagekitd (code=dumped, signal=TRAP)
 Main PID: 31837 (code=dumped, signal=TRAP)

set 26 16:52:37 erico-xps systemd[1]: Starting PackageKit Daemon...
set 26 16:52:37 erico-xps PackageKit[31837]: daemon start
set 26 16:52:37 erico-xps packagekitd[31837]: Failed to initialize alpm: using /etc/PackageKit/alpm.d/pacman.conf: /etc/PackageKit/alpm.d/pacman.conf:8/etc/pacman.conf:17unrecognised directive 'HookDir'
set 26 16:52:37 erico-xps systemd[1]: packagekit.service: Main process exited, code=dumped, status=5/TRAP
set 26 16:52:37 erico-xps systemd[1]: packagekit.service: Failed with result 'core-dump'.
set 26 16:52:37 erico-xps systemd[1]: Failed to start PackageKit Daemon.
```

**Steps to reproduce the problem**

You just need a `HookDir` directive in the `[options]` header in `/etc/pacman.conf`.

**Observation**

* This issue has been present since 2016, at least: https://bbs.archlinux.org/viewtopic.php?id=213009
* https://bugs.freedesktop.org/enter_bug.cgi?product=PackageKit doesn't allow reporting bugs for PackageKit, nor is it available on freedesktop's GitLab instance.
* I am interested in implementing the necessary fix, but I would need to know whether it's best to ignore all unknown directives or just make the `HookDir` directive "known".

### PR DESCRIPTION
**Pull request by adrianinsaval**
~Note that I have not tested this,~ just looked at 

https://github.com/PackageKit/PackageKit/blob/7e700e2177ca3f84ea5a2978cdf687179b3445a9/backends/alpm/pk-alpm-config.c#L1017
and 
https://github.com/devkitPro/pacman/blob/49b08fa9d14a9cc06f01c624c644cb987ce97642/lib/libalpm/alpm.h#L1732

and thought it was a copy paste error.

### CODE REVIEW

**Comment by aleixpol** [comment]
Can you maybe test it then?

**Comment by adrianinsaval** [comment]
Sorry, I'm short of time to figure out how to compile this right now, perhaps next week. But that there is an error in the code is pretty evident IMO

**Comment by adrianinsaval** [comment]
now I actually tested and it does fix the issue after correcting the alphabetical order of `pk_alpm_config_list_options`, there was a comment there specifying that the order should be respected but this was not taken into account for that change.
Also confirmed that the option is respected and the hooks in the custom dir are being run

**Comment by adrianinsaval** [comment]
This is ready for merge IMO, I fixed another bug where the system hook dir (default `/usr/share/libalpm/hooks/`) was being overridden and ignored instead of just adding the additional hookdirs as it was supposed, the fix is based on this: https://gitlab.archlinux.org/pacman/pacman/-/blob/master/lib/libalpm/handle.c#L452

File: backends/alpm/pk-alpm-config.c [hunk 1]
```diff
@@ -1014,7 +1014,10 @@ pk_alpm_config_configure_alpm (PkBackend *backend, PkAlpmConfig *config, GError
 	config->noupgrades = NULL;
 
 	/* alpm takes ownership */
-	alpm_option_set_noupgrades (handle, config->hookdirs);
+	alpm_list_t *j;
+	for(j = config->hookdirs; j; j = j->next) {
```
Comment (hughsie) [inline backends/alpm/pk-alpm-config.c:1018]: can you put the alpm_list_t in the loop please, and squash all these down to a single commit pls

Comment (adrianinsaval) [reply backends/alpm/pk-alpm-config.c:1018]: I can squash no problem but I don't know how to put alpm_list_t inside the loop, it's the variable used to iterate, don't I need it declared beforehand?

Comment (hughsie) [reply backends/alpm/pk-alpm-config.c:1018]: `for(alpm_list_t *j = config->hookdirs; `

Comment (adrianinsaval) [reply backends/alpm/pk-alpm-config.c]: done

**Comment by adrianinsaval** [comment]
thanks, any clue when this would be in a release? In the mean time I'll ask again the archlinux packagers to apply this patch.
